name: CI/CD Pipeline for Kubernetes
on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up Go
     uses: actions/setup-go@v3
     with:
       go-version: '1.18'
   - name: Install dependencies
     run: |
       sudo apt-get update
       sudo apt-get install -y make gcc
   - name: Build Kubernetes
     run: |
       make
   - name: Test Kubernetes
     run: |
       make test
   - name: Build Docker image
     run: |
       docker build -t your-dockerhub-username/kubernetes:latest .
   - name: Push Docker image
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     run: |
       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       docker push your-dockerhub-username/kubernetes:latest
 deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up Kubectl
     uses: azure/setup-kubectl@v3
     with:
       version: 'latest'
   - name: Deploy to Kubernetes
     env:
       KUBECONFIG: ${{ secrets.KUBECONFIG }}
     run: |
       kubectl apply -f k8s/deployment.yaml
